service: sls-upload-file
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"

functions:
  uploadFile:
    handler: handler.uploadFile
    events:
      - http:
          path: /file/upload
          method: post
          cors: true

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: file-upload-bucket
        AccessControl: PublicRead
