service: sls-upload-file
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  uploadFile:
    handler: handler.uploadFile
    events:
      - http:
          path: /file-upload
          method: post
          cors: true
    environment:
      BUCKET: file-upload-bucket-comosus

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: file-upload-bucket-comosus
        AccessControl: PublicRead
